services:


  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - "80:4455"
      - "443:4455"
      - "4455:4455"
      - "4456:4456"
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./ory/oathkeeper:/etc/config/oathkeeper


  kratos-migrate:
    image: oryd/kratos:v0.10.0
    volumes:
      - ./ory/kratos:/etc/config/kratos
      - kratos-config:/home/ory
      - kratos-config:/var/lib/sqlite
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet


  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ./ory/kratos:/etc/config/kratos
      - kratos-config:/home/ory
      - kratos-config:/var/lib/sqlite
    networks:
      - intranet


  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.10.0
    ports:
      - "4466:4466"
    environment:
      - PORT=4466
      - BASE_URL=/auth
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=https://dev.thielker.net/kratos
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
    networks:
      - intranet
    restart: on-failure


  kratos-database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - kratos-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet


  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet


networks:
  intranet:


volumes:
  oathkeeper-config:
  kratos-config:
  kratos-data:
