- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /kratos
  match:
    url: "https://dev.thielker.net/kratos/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop


- id: "ory:kratos-ui:anonymous"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4466"
    strip_path: /auth
  match:
    url: "https://dev.thielker.net/auth/<{registration,welcome,recovery,verification,login,error,**.css,**.js,**.png,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop


- id: "ory:kratos-ui:protected"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4466"
    strip_path: /auth
  match:
    url: "https://dev.thielker.net/auth/<{debug,dashboard,settings}>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: https://dev.thielker.net/login
