log:
  level: warning
  format: text


dsn: postgres://kratos:secret@kratos-database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4


serve:
  public:
    base_url: https://dev.thielker.net/kratos
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/


selfservice:
  default_browser_return_url: https://dev.thielker.net/
  allowed_return_urls:
    - https://dev.thielker.net/

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: /auth/error

    settings:
      ui_url: /auth/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: /auth/recovery

    verification:
      enabled: true
      ui_url: /auth/verification
      after:
        default_browser_return_url: /auth/welcome

    logout:
      after:
        default_browser_return_url: /auth/login

    login:
      ui_url: /auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: /auth/registration
      after:
        password:
          hooks:
            - hook: session


secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL


ciphers:
  algorithm: xchacha20-poly1305


hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8


identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json


courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
